version: '3'  # Docker Composeのバージョン
services:
  web:  # コンテナに名前をつける
    build: .  # Dockerfileがあるディレクトリへのパス
    volumes:
      - .:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8080:8080"
    command: npm run serve
